sbatch arab_s10_train.sh
sbatch arab_s1_train.sh
sbatch arab_s2_train.sh
sbatch arab_s3_train.sh
sbatch arab_s4_train.sh
sbatch arab_s5_train.sh
sbatch arab_s6_train.sh
sbatch arab_s7_train.sh
sbatch arab_s8_train.sh
sbatch arab_s9_train.sh
sbatch fin_s10_train.sh
sbatch fin_s1_train.sh
sbatch fin_s2_train.sh
sbatch fin_s3_train.sh
sbatch fin_s4_train.sh
sbatch fin_s5_train.sh
sbatch fin_s6_train.sh
sbatch fin_s7_train.sh
sbatch fin_s8_train.sh
sbatch fin_s9_train.sh
sbatch geor_s10_train.sh
sbatch geor_s1_train.sh
sbatch geor_s2_train.sh
sbatch geor_s3_train.sh
sbatch geor_s4_train.sh
sbatch geor_s5_train.sh
sbatch geor_s6_train.sh
sbatch geor_s7_train.sh
sbatch geor_s8_train.sh
sbatch geor_s9_train.sh
sbatch ger_s10_train.sh
sbatch ger_s1_train.sh
sbatch ger_s2_train.sh
sbatch ger_s3_train.sh
sbatch ger_s4_train.sh
sbatch ger_s5_train.sh
sbatch ger_s6_train.sh
sbatch ger_s7_train.sh
sbatch ger_s8_train.sh
sbatch ger_s9_train.sh
sbatch hin_s10_train.sh
sbatch hin_s1_train.sh
sbatch hin_s2_train.sh
sbatch hin_s3_train.sh
sbatch hin_s4_train.sh
sbatch hin_s5_train.sh
sbatch hin_s6_train.sh
sbatch hin_s7_train.sh
sbatch hin_s8_train.sh
sbatch hin_s9_train.sh
sbatch ita_s10_train.sh
sbatch ita_s1_train.sh
sbatch ita_s2_train.sh
sbatch ita_s3_train.sh
sbatch ita_s4_train.sh
sbatch ita_s5_train.sh
sbatch ita_s6_train.sh
sbatch ita_s7_train.sh
sbatch ita_s8_train.sh
sbatch ita_s9_train.sh
sbatch kha_s10_train.sh
sbatch kha_s1_train.sh
sbatch kha_s2_train.sh
sbatch kha_s3_train.sh
sbatch kha_s4_train.sh
sbatch kha_s5_train.sh
sbatch kha_s6_train.sh
sbatch kha_s7_train.sh
sbatch kha_s8_train.sh
sbatch kha_s9_train.sh
sbatch nav_s10_train.sh
sbatch nav_s1_train.sh
sbatch nav_s2_train.sh
sbatch nav_s3_train.sh
sbatch nav_s4_train.sh
sbatch nav_s5_train.sh
sbatch nav_s6_train.sh
sbatch nav_s7_train.sh
sbatch nav_s8_train.sh
sbatch nav_s9_train.sh
sbatch rus_s10_train.sh
sbatch rus_s1_train.sh
sbatch rus_s2_train.sh
sbatch rus_s3_train.sh
sbatch rus_s4_train.sh
sbatch rus_s5_train.sh
sbatch rus_s6_train.sh
sbatch rus_s7_train.sh
sbatch rus_s8_train.sh
sbatch rus_s9_train.sh
sbatch tur_s10_train.sh
sbatch tur_s1_train.sh
sbatch tur_s2_train.sh
sbatch tur_s3_train.sh
sbatch tur_s4_train.sh
sbatch tur_s5_train.sh
sbatch tur_s6_train.sh
sbatch tur_s7_train.sh
sbatch tur_s8_train.sh
sbatch tur_s9_train.sh

