sbatch train_arabic_s1.sh
sbatch train_arabic_s2.sh
sbatch train_arabic_s3.sh
sbatch train_arabic_s4.sh
sbatch train_arabic_s5.sh
sbatch train_arabic_s6.sh
sbatch train_arabic_s7.sh
sbatch train_arabic_s8.sh
sbatch train_arabic_s9.sh
sbatch train_arabic_s10.sh
sbatch train_finnish_s1.sh
sbatch train_finnish_s2.sh
sbatch train_finnish_s3.sh
sbatch train_finnish_s4.sh
sbatch train_finnish_s5.sh
sbatch train_finnish_s6.sh
sbatch train_finnish_s7.sh
sbatch train_finnish_s8.sh
sbatch train_finnish_s9.sh
sbatch train_finnish_s10.sh
sbatch train_georgian_s1.sh
sbatch train_georgian_s2.sh
sbatch train_georgian_s3.sh
sbatch train_georgian_s4.sh
sbatch train_georgian_s5.sh
sbatch train_georgian_s6.sh
sbatch train_georgian_s7.sh
sbatch train_georgian_s8.sh
sbatch train_georgian_s9.sh
sbatch train_georgian_s10.sh
sbatch train_german_s1.sh
sbatch train_german_s2.sh
sbatch train_german_s3.sh
sbatch train_german_s4.sh
sbatch train_german_s5.sh
sbatch train_german_s6.sh
sbatch train_german_s7.sh
sbatch train_german_s8.sh
sbatch train_german_s9.sh
sbatch train_german_s10.sh
sbatch train_hindi_s1.sh
sbatch train_hindi_s2.sh
sbatch train_hindi_s3.sh
sbatch train_hindi_s4.sh
sbatch train_hindi_s5.sh
sbatch train_hindi_s6.sh
sbatch train_hindi_s7.sh
sbatch train_hindi_s8.sh
sbatch train_hindi_s9.sh
sbatch train_hindi_s10.sh
sbatch train_italian_s1.sh
sbatch train_italian_s2.sh
sbatch train_italian_s3.sh
sbatch train_italian_s4.sh
sbatch train_italian_s5.sh
sbatch train_italian_s6.sh
sbatch train_italian_s7.sh
sbatch train_italian_s8.sh
sbatch train_italian_s9.sh
sbatch train_italian_s10.sh
sbatch train_khaling_s1.sh
sbatch train_khaling_s2.sh
sbatch train_khaling_s3.sh
sbatch train_khaling_s4.sh
sbatch train_khaling_s5.sh
sbatch train_khaling_s6.sh
sbatch train_khaling_s7.sh
sbatch train_khaling_s8.sh
sbatch train_khaling_s9.sh
sbatch train_khaling_s10.sh
sbatch train_navajo_s1.sh
sbatch train_navajo_s2.sh
sbatch train_navajo_s3.sh
sbatch train_navajo_s4.sh
sbatch train_navajo_s5.sh
sbatch train_navajo_s6.sh
sbatch train_navajo_s7.sh
sbatch train_navajo_s8.sh
sbatch train_navajo_s9.sh
sbatch train_navajo_s10.sh
sbatch train_russian_s1.sh
sbatch train_russian_s2.sh
sbatch train_russian_s3.sh
sbatch train_russian_s4.sh
sbatch train_russian_s5.sh
sbatch train_russian_s6.sh
sbatch train_russian_s7.sh
sbatch train_russian_s8.sh
sbatch train_russian_s9.sh
sbatch train_russian_s10.sh
sbatch train_turkish_s1.sh
sbatch train_turkish_s2.sh
sbatch train_turkish_s3.sh
sbatch train_turkish_s4.sh
sbatch train_turkish_s5.sh
sbatch train_turkish_s6.sh
sbatch train_turkish_s7.sh
sbatch train_turkish_s8.sh
sbatch train_turkish_s9.sh
sbatch train_turkish_s10.sh
